ALTER TABLE wallets
    ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT 'fa-solid fa-wallet',
    ADD COLUMN IF NOT EXISTS color VARCHAR(9) NOT NULL DEFAULT '#22c55e';

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT 'fa-solid fa-tag',
    ADD COLUMN IF NOT EXISTS color VARCHAR(9) NOT NULL DEFAULT '#6366f1';

ALTER TABLE goals
    ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT 'fa-solid fa-bullseye',
    ADD COLUMN IF NOT EXISTS color VARCHAR(9) NOT NULL DEFAULT '#f97316';
